/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomId = IDL.Nat;
export const UserRole = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'consultant' : IDL.Null,
  'engineer' : IDL.Null,
  'analyst' : IDL.Null,
});
export const Profile = IDL.Record({
  'displayName' : IDL.Text,
  'role' : UserRole,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const RoomCode = IDL.Nat;
export const RoomView = IDL.Record({
  'id' : RoomId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'participants' : IDL.Vec(IDL.Principal),
  'code' : RoomCode,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createRoom' : IDL.Func([IDL.Text, IDL.Text], [RoomId], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMessages' : IDL.Func([RoomId], [IDL.Vec(Message)], ['query']),
  'getMyRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
  'getNote' : IDL.Func([RoomId], [IDL.Text], ['query']),
  'getRoomParticipants' : IDL.Func(
      [RoomId],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([RoomCode], [], []),
  'leaveRoom' : IDL.Func([RoomId], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'saveNote' : IDL.Func([RoomId, IDL.Text], [], []),
  'sendMessage' : IDL.Func([RoomId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomId = IDL.Nat;
  const UserRole = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'consultant' : IDL.Null,
    'engineer' : IDL.Null,
    'analyst' : IDL.Null,
  });
  const Profile = IDL.Record({ 'displayName' : IDL.Text, 'role' : UserRole });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const RoomCode = IDL.Nat;
  const RoomView = IDL.Record({
    'id' : RoomId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'participants' : IDL.Vec(IDL.Principal),
    'code' : RoomCode,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createRoom' : IDL.Func([IDL.Text, IDL.Text], [RoomId], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMessages' : IDL.Func([RoomId], [IDL.Vec(Message)], ['query']),
    'getMyRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
    'getNote' : IDL.Func([RoomId], [IDL.Text], ['query']),
    'getRoomParticipants' : IDL.Func(
        [RoomId],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([RoomCode], [], []),
    'leaveRoom' : IDL.Func([RoomId], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'saveNote' : IDL.Func([RoomId, IDL.Text], [], []),
    'sendMessage' : IDL.Func([RoomId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };