/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface Profile { 'displayName' : string, 'role' : UserRole }
export type RoomCode = bigint;
export type RoomId = bigint;
export interface RoomView {
  'id' : RoomId,
  'title' : string,
  'creator' : Principal,
  'participants' : Array<Principal>,
  'code' : RoomCode,
  'description' : string,
}
export type Time = bigint;
export type UserRole = { 'client' : null } |
  { 'admin' : null } |
  { 'consultant' : null } |
  { 'engineer' : null } |
  { 'analyst' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createRoom' : ActorMethod<[string, string], RoomId>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMessages' : ActorMethod<[RoomId], Array<Message>>,
  'getMyRooms' : ActorMethod<[], Array<RoomView>>,
  'getNote' : ActorMethod<[RoomId], string>,
  'getRoomParticipants' : ActorMethod<[RoomId], Array<[Principal, Profile]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<[RoomCode], undefined>,
  'leaveRoom' : ActorMethod<[RoomId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'saveNote' : ActorMethod<[RoomId, string], undefined>,
  'sendMessage' : ActorMethod<[RoomId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];